[package]
name = "strings_and_arrays_3"
version = "0.1.0"
authors = ["Sebastian <sebschwieger@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
